/**
 * Animation / combo frame data — separate from talent kits.
 * Regenerated by: node scripts/extractAnimationTimings.mjs
 */

export type AnimationSource = 'gcsim' | 'estimated' | 'manual' | null

export type AnimationCancelMap = {
  attack?: number
  charge?: number
  skill?: number
  burst?: number
  dash?: number
  jump?: number
  walk?: number
  swap?: number
  aim?: number
}

export type AnimationAction = {
  id: string
  label: string
  /** Stable kind: na1, ca, ca_cycle, skill, skill_hold, burst, plunge_high, dash, … */
  kind: string
  /** Full animation length @ fps (usually 60). */
  frames: number | null
  /** Optional max length for hold/spin actions (e.g. Mavuika CA donut). */
  framesMax?: number | null
  seconds: number | null
  secondsMax?: number | null
  /** Hit frame offsets from action start. */
  hitmarks: number[]
  /** Frames per revolution for spin/donut charged attacks. */
  spinFrames?: number | null
  cancels: AnimationCancelMap
  source: AnimationSource
  notes?: string
  gcsimVar?: string
}

export type AnimationState = {
  id: string
  label: string
  actions: AnimationAction[]
}

export type CharacterAnimationTimings = {
  id: string
  name: string
  fps: number
  gcsimPackage: string | null
  /** Present when frames came from an open gcsim PR overlay (fetchGcsimPrChars). */
  gcsimPr?: {
    number: number | null
    repo: string | null
    branch: string | null
  } | null
  sources: string[]
  completeness: {
    actionsWithFrames: number
    actionsTotal: number
  }
  incomplete: boolean
  states: AnimationState[]
  notes?: string
}

export type CharacterAnimationTimingsFile = {
  source: string
  extractedAt: string
  fps: number
  notes: string[]
  count: number
  withGcsim: number
  characters: CharacterAnimationTimings[]
}
